{
 "title": "FastAPI Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(starlette_request_duration_seconds_count{job=\"fastapi-service\"}[5m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(starlette_request_duration_seconds_sum{job=\"fastapi-service\"}[5m]) / rate(starlette_request_duration_seconds_count{job=\"fastapi-service\"}[5m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Success vs Fail Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(starlette_requests_total{job=\"fastapi-service\", status_code=~\"2..\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(starlette_requests_total{job=\"fastapi-service\", status_code=~\"[45]..\"}[5m]))",
     "legendFormat": "Fail"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"fastapi-service\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  }
 ]
}